# coding: utf-8

"""
    Swagger Petstore

    This is a sample Petstore server.  You can find  out more about Swagger at  [http://swagger.io](http://swagger.io) or on  [irc.freenode.net, #swagger](http://swagger.io/irc/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.smart_nvme_temperature import SmartNvmeTemperature  # noqa: E501
from swagger_client.rest import ApiException


class TestSmartNvmeTemperature(unittest.TestCase):
    """SmartNvmeTemperature unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSmartNvmeTemperature(self):
        """Test SmartNvmeTemperature"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.smart_nvme_temperature.SmartNvmeTemperature()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
