# coding: utf-8

"""
    Swagger Petstore

    This is a sample Petstore server.  You can find  out more about Swagger at  [http://swagger.io](http://swagger.io) or on  [irc.freenode.net, #swagger](http://swagger.io/irc/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.smart_data_api import SmartDataApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSmartDataApi(unittest.TestCase):
    """SmartDataApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.smart_data_api.SmartDataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_smart_nvme(self):
        """Test case for add_smart_nvme

        Upload NVME disk data  # noqa: E501
        """
        pass

    def test_add_smart_ssd(self):
        """Test case for add_smart_ssd

        Upload ssd disk data  # noqa: E501
        """
        pass

    def test_get_smart_nvme(self):
        """Test case for get_smart_nvme

        Get all NVME disk data  # noqa: E501
        """
        pass

    def test_get_smart_ssd(self):
        """Test case for get_smart_ssd

        Get all ssd disk data  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
