# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SmartNvmeTemperature(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, current: int=None):  # noqa: E501
        """SmartNvmeTemperature - a model defined in Swagger

        :param current: The current of this SmartNvmeTemperature.  # noqa: E501
        :type current: int
        """
        self.swagger_types = {
            'current': int
        }

        self.attribute_map = {
            'current': 'current'
        }

        self._current = current

    @classmethod
    def from_dict(cls, dikt) -> 'SmartNvmeTemperature':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SmartNvme_temperature of this SmartNvmeTemperature.  # noqa: E501
        :rtype: SmartNvmeTemperature
        """
        return util.deserialize_model(dikt, cls)

    @property
    def current(self) -> int:
        """Gets the current of this SmartNvmeTemperature.


        :return: The current of this SmartNvmeTemperature.
        :rtype: int
        """
        return self._current

    @current.setter
    def current(self, current: int):
        """Sets the current of this SmartNvmeTemperature.


        :param current: The current of this SmartNvmeTemperature.
        :type current: int
        """

        self._current = current
