# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SmartSsdAtaSctCapabilities(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, value: int=None, error_recovery_control_supported: bool=None, feature_control_supported: bool=None, data_table_supported: bool=None):  # noqa: E501
        """SmartSsdAtaSctCapabilities - a model defined in Swagger

        :param value: The value of this SmartSsdAtaSctCapabilities.  # noqa: E501
        :type value: int
        :param error_recovery_control_supported: The error_recovery_control_supported of this SmartSsdAtaSctCapabilities.  # noqa: E501
        :type error_recovery_control_supported: bool
        :param feature_control_supported: The feature_control_supported of this SmartSsdAtaSctCapabilities.  # noqa: E501
        :type feature_control_supported: bool
        :param data_table_supported: The data_table_supported of this SmartSsdAtaSctCapabilities.  # noqa: E501
        :type data_table_supported: bool
        """
        self.swagger_types = {
            'value': int,
            'error_recovery_control_supported': bool,
            'feature_control_supported': bool,
            'data_table_supported': bool
        }

        self.attribute_map = {
            'value': 'value',
            'error_recovery_control_supported': 'error_recovery_control_supported',
            'feature_control_supported': 'feature_control_supported',
            'data_table_supported': 'data_table_supported'
        }

        self._value = value
        self._error_recovery_control_supported = error_recovery_control_supported
        self._feature_control_supported = feature_control_supported
        self._data_table_supported = data_table_supported

    @classmethod
    def from_dict(cls, dikt) -> 'SmartSsdAtaSctCapabilities':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SmartSsd_ata_sct_capabilities of this SmartSsdAtaSctCapabilities.  # noqa: E501
        :rtype: SmartSsdAtaSctCapabilities
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self) -> int:
        """Gets the value of this SmartSsdAtaSctCapabilities.


        :return: The value of this SmartSsdAtaSctCapabilities.
        :rtype: int
        """
        return self._value

    @value.setter
    def value(self, value: int):
        """Sets the value of this SmartSsdAtaSctCapabilities.


        :param value: The value of this SmartSsdAtaSctCapabilities.
        :type value: int
        """

        self._value = value

    @property
    def error_recovery_control_supported(self) -> bool:
        """Gets the error_recovery_control_supported of this SmartSsdAtaSctCapabilities.


        :return: The error_recovery_control_supported of this SmartSsdAtaSctCapabilities.
        :rtype: bool
        """
        return self._error_recovery_control_supported

    @error_recovery_control_supported.setter
    def error_recovery_control_supported(self, error_recovery_control_supported: bool):
        """Sets the error_recovery_control_supported of this SmartSsdAtaSctCapabilities.


        :param error_recovery_control_supported: The error_recovery_control_supported of this SmartSsdAtaSctCapabilities.
        :type error_recovery_control_supported: bool
        """

        self._error_recovery_control_supported = error_recovery_control_supported

    @property
    def feature_control_supported(self) -> bool:
        """Gets the feature_control_supported of this SmartSsdAtaSctCapabilities.


        :return: The feature_control_supported of this SmartSsdAtaSctCapabilities.
        :rtype: bool
        """
        return self._feature_control_supported

    @feature_control_supported.setter
    def feature_control_supported(self, feature_control_supported: bool):
        """Sets the feature_control_supported of this SmartSsdAtaSctCapabilities.


        :param feature_control_supported: The feature_control_supported of this SmartSsdAtaSctCapabilities.
        :type feature_control_supported: bool
        """

        self._feature_control_supported = feature_control_supported

    @property
    def data_table_supported(self) -> bool:
        """Gets the data_table_supported of this SmartSsdAtaSctCapabilities.


        :return: The data_table_supported of this SmartSsdAtaSctCapabilities.
        :rtype: bool
        """
        return self._data_table_supported

    @data_table_supported.setter
    def data_table_supported(self, data_table_supported: bool):
        """Sets the data_table_supported of this SmartSsdAtaSctCapabilities.


        :param data_table_supported: The data_table_supported of this SmartSsdAtaSctCapabilities.
        :type data_table_supported: bool
        """

        self._data_table_supported = data_table_supported
