# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SmartSsdAtaSmartDataSelfTestStatus(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, value: int=None, string: str=None, passed: bool=None):  # noqa: E501
        """SmartSsdAtaSmartDataSelfTestStatus - a model defined in Swagger

        :param value: The value of this SmartSsdAtaSmartDataSelfTestStatus.  # noqa: E501
        :type value: int
        :param string: The string of this SmartSsdAtaSmartDataSelfTestStatus.  # noqa: E501
        :type string: str
        :param passed: The passed of this SmartSsdAtaSmartDataSelfTestStatus.  # noqa: E501
        :type passed: bool
        """
        self.swagger_types = {
            'value': int,
            'string': str,
            'passed': bool
        }

        self.attribute_map = {
            'value': 'value',
            'string': 'string',
            'passed': 'passed'
        }

        self._value = value
        self._string = string
        self._passed = passed

    @classmethod
    def from_dict(cls, dikt) -> 'SmartSsdAtaSmartDataSelfTestStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SmartSsd_ata_smart_data_self_test_status of this SmartSsdAtaSmartDataSelfTestStatus.  # noqa: E501
        :rtype: SmartSsdAtaSmartDataSelfTestStatus
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self) -> int:
        """Gets the value of this SmartSsdAtaSmartDataSelfTestStatus.


        :return: The value of this SmartSsdAtaSmartDataSelfTestStatus.
        :rtype: int
        """
        return self._value

    @value.setter
    def value(self, value: int):
        """Sets the value of this SmartSsdAtaSmartDataSelfTestStatus.


        :param value: The value of this SmartSsdAtaSmartDataSelfTestStatus.
        :type value: int
        """

        self._value = value

    @property
    def string(self) -> str:
        """Gets the string of this SmartSsdAtaSmartDataSelfTestStatus.


        :return: The string of this SmartSsdAtaSmartDataSelfTestStatus.
        :rtype: str
        """
        return self._string

    @string.setter
    def string(self, string: str):
        """Sets the string of this SmartSsdAtaSmartDataSelfTestStatus.


        :param string: The string of this SmartSsdAtaSmartDataSelfTestStatus.
        :type string: str
        """

        self._string = string

    @property
    def passed(self) -> bool:
        """Gets the passed of this SmartSsdAtaSmartDataSelfTestStatus.


        :return: The passed of this SmartSsdAtaSmartDataSelfTestStatus.
        :rtype: bool
        """
        return self._passed

    @passed.setter
    def passed(self, passed: bool):
        """Sets the passed of this SmartSsdAtaSmartDataSelfTestStatus.


        :param passed: The passed of this SmartSsdAtaSmartDataSelfTestStatus.
        :type passed: bool
        """

        self._passed = passed
