# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SmartNvmeSize(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, blocks: int=None, bytes: int=None):  # noqa: E501
        """SmartNvmeSize - a model defined in Swagger

        :param blocks: The blocks of this SmartNvmeSize.  # noqa: E501
        :type blocks: int
        :param bytes: The bytes of this SmartNvmeSize.  # noqa: E501
        :type bytes: int
        """
        self.swagger_types = {
            'blocks': int,
            'bytes': int
        }

        self.attribute_map = {
            'blocks': 'blocks',
            'bytes': 'bytes'
        }

        self._blocks = blocks
        self._bytes = bytes

    @classmethod
    def from_dict(cls, dikt) -> 'SmartNvmeSize':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SmartNvme_size of this SmartNvmeSize.  # noqa: E501
        :rtype: SmartNvmeSize
        """
        return util.deserialize_model(dikt, cls)

    @property
    def blocks(self) -> int:
        """Gets the blocks of this SmartNvmeSize.


        :return: The blocks of this SmartNvmeSize.
        :rtype: int
        """
        return self._blocks

    @blocks.setter
    def blocks(self, blocks: int):
        """Sets the blocks of this SmartNvmeSize.


        :param blocks: The blocks of this SmartNvmeSize.
        :type blocks: int
        """

        self._blocks = blocks

    @property
    def bytes(self) -> int:
        """Gets the bytes of this SmartNvmeSize.


        :return: The bytes of this SmartNvmeSize.
        :rtype: int
        """
        return self._bytes

    @bytes.setter
    def bytes(self, bytes: int):
        """Sets the bytes of this SmartNvmeSize.


        :param bytes: The bytes of this SmartNvmeSize.
        :type bytes: int
        """

        self._bytes = bytes
