# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.smart_ssd_ata_smart_attributes_table import SmartSsdAtaSmartAttributesTable  # noqa: F401,E501
from swagger_server import util


class SmartSsdAtaSmartAttributes(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, revision: int=None, table: List[SmartSsdAtaSmartAttributesTable]=None):  # noqa: E501
        """SmartSsdAtaSmartAttributes - a model defined in Swagger

        :param revision: The revision of this SmartSsdAtaSmartAttributes.  # noqa: E501
        :type revision: int
        :param table: The table of this SmartSsdAtaSmartAttributes.  # noqa: E501
        :type table: List[SmartSsdAtaSmartAttributesTable]
        """
        self.swagger_types = {
            'revision': int,
            'table': List[SmartSsdAtaSmartAttributesTable]
        }

        self.attribute_map = {
            'revision': 'revision',
            'table': 'table'
        }

        self._revision = revision
        self._table = table

    @classmethod
    def from_dict(cls, dikt) -> 'SmartSsdAtaSmartAttributes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SmartSsd_ata_smart_attributes of this SmartSsdAtaSmartAttributes.  # noqa: E501
        :rtype: SmartSsdAtaSmartAttributes
        """
        return util.deserialize_model(dikt, cls)

    @property
    def revision(self) -> int:
        """Gets the revision of this SmartSsdAtaSmartAttributes.


        :return: The revision of this SmartSsdAtaSmartAttributes.
        :rtype: int
        """
        return self._revision

    @revision.setter
    def revision(self, revision: int):
        """Sets the revision of this SmartSsdAtaSmartAttributes.


        :param revision: The revision of this SmartSsdAtaSmartAttributes.
        :type revision: int
        """

        self._revision = revision

    @property
    def table(self) -> List[SmartSsdAtaSmartAttributesTable]:
        """Gets the table of this SmartSsdAtaSmartAttributes.


        :return: The table of this SmartSsdAtaSmartAttributes.
        :rtype: List[SmartSsdAtaSmartAttributesTable]
        """
        return self._table

    @table.setter
    def table(self, table: List[SmartSsdAtaSmartAttributesTable]):
        """Sets the table of this SmartSsdAtaSmartAttributes.


        :param table: The table of this SmartSsdAtaSmartAttributes.
        :type table: List[SmartSsdAtaSmartAttributesTable]
        """

        self._table = table
