# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SmartSsdWwn(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, naa: int=None, oui: int=None, id: int=None):  # noqa: E501
        """SmartSsdWwn - a model defined in Swagger

        :param naa: The naa of this SmartSsdWwn.  # noqa: E501
        :type naa: int
        :param oui: The oui of this SmartSsdWwn.  # noqa: E501
        :type oui: int
        :param id: The id of this SmartSsdWwn.  # noqa: E501
        :type id: int
        """
        self.swagger_types = {
            'naa': int,
            'oui': int,
            'id': int
        }

        self.attribute_map = {
            'naa': 'naa',
            'oui': 'oui',
            'id': 'id'
        }

        self._naa = naa
        self._oui = oui
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'SmartSsdWwn':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SmartSsd_wwn of this SmartSsdWwn.  # noqa: E501
        :rtype: SmartSsdWwn
        """
        return util.deserialize_model(dikt, cls)

    @property
    def naa(self) -> int:
        """Gets the naa of this SmartSsdWwn.


        :return: The naa of this SmartSsdWwn.
        :rtype: int
        """
        return self._naa

    @naa.setter
    def naa(self, naa: int):
        """Sets the naa of this SmartSsdWwn.


        :param naa: The naa of this SmartSsdWwn.
        :type naa: int
        """

        self._naa = naa

    @property
    def oui(self) -> int:
        """Gets the oui of this SmartSsdWwn.


        :return: The oui of this SmartSsdWwn.
        :rtype: int
        """
        return self._oui

    @oui.setter
    def oui(self, oui: int):
        """Sets the oui of this SmartSsdWwn.


        :param oui: The oui of this SmartSsdWwn.
        :type oui: int
        """

        self._oui = oui

    @property
    def id(self) -> int:
        """Gets the id of this SmartSsdWwn.


        :return: The id of this SmartSsdWwn.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this SmartSsdWwn.


        :param id: The id of this SmartSsdWwn.
        :type id: int
        """

        self._id = id
