# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.smart_ssd_sata_phy_event_counters_table import SmartSsdSataPhyEventCountersTable  # noqa: F401,E501
from swagger_server import util


class SmartSsdSataPhyEventCounters(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, table: List[SmartSsdSataPhyEventCountersTable]=None, reset: bool=None):  # noqa: E501
        """SmartSsdSataPhyEventCounters - a model defined in Swagger

        :param table: The table of this SmartSsdSataPhyEventCounters.  # noqa: E501
        :type table: List[SmartSsdSataPhyEventCountersTable]
        :param reset: The reset of this SmartSsdSataPhyEventCounters.  # noqa: E501
        :type reset: bool
        """
        self.swagger_types = {
            'table': List[SmartSsdSataPhyEventCountersTable],
            'reset': bool
        }

        self.attribute_map = {
            'table': 'table',
            'reset': 'reset'
        }

        self._table = table
        self._reset = reset

    @classmethod
    def from_dict(cls, dikt) -> 'SmartSsdSataPhyEventCounters':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SmartSsd_sata_phy_event_counters of this SmartSsdSataPhyEventCounters.  # noqa: E501
        :rtype: SmartSsdSataPhyEventCounters
        """
        return util.deserialize_model(dikt, cls)

    @property
    def table(self) -> List[SmartSsdSataPhyEventCountersTable]:
        """Gets the table of this SmartSsdSataPhyEventCounters.


        :return: The table of this SmartSsdSataPhyEventCounters.
        :rtype: List[SmartSsdSataPhyEventCountersTable]
        """
        return self._table

    @table.setter
    def table(self, table: List[SmartSsdSataPhyEventCountersTable]):
        """Sets the table of this SmartSsdSataPhyEventCounters.


        :param table: The table of this SmartSsdSataPhyEventCounters.
        :type table: List[SmartSsdSataPhyEventCountersTable]
        """

        self._table = table

    @property
    def reset(self) -> bool:
        """Gets the reset of this SmartSsdSataPhyEventCounters.


        :return: The reset of this SmartSsdSataPhyEventCounters.
        :rtype: bool
        """
        return self._reset

    @reset.setter
    def reset(self, reset: bool):
        """Sets the reset of this SmartSsdSataPhyEventCounters.


        :param reset: The reset of this SmartSsdSataPhyEventCounters.
        :type reset: bool
        """

        self._reset = reset
