# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.smart_ssd_read_lookahead import SmartSsdReadLookahead  # noqa: F401,E501
from swagger_server import util


class SmartSsdAtaSctErc(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, read: SmartSsdReadLookahead=None, write: SmartSsdReadLookahead=None):  # noqa: E501
        """SmartSsdAtaSctErc - a model defined in Swagger

        :param read: The read of this SmartSsdAtaSctErc.  # noqa: E501
        :type read: SmartSsdReadLookahead
        :param write: The write of this SmartSsdAtaSctErc.  # noqa: E501
        :type write: SmartSsdReadLookahead
        """
        self.swagger_types = {
            'read': SmartSsdReadLookahead,
            'write': SmartSsdReadLookahead
        }

        self.attribute_map = {
            'read': 'read',
            'write': 'write'
        }

        self._read = read
        self._write = write

    @classmethod
    def from_dict(cls, dikt) -> 'SmartSsdAtaSctErc':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SmartSsd_ata_sct_erc of this SmartSsdAtaSctErc.  # noqa: E501
        :rtype: SmartSsdAtaSctErc
        """
        return util.deserialize_model(dikt, cls)

    @property
    def read(self) -> SmartSsdReadLookahead:
        """Gets the read of this SmartSsdAtaSctErc.


        :return: The read of this SmartSsdAtaSctErc.
        :rtype: SmartSsdReadLookahead
        """
        return self._read

    @read.setter
    def read(self, read: SmartSsdReadLookahead):
        """Sets the read of this SmartSsdAtaSctErc.


        :param read: The read of this SmartSsdAtaSctErc.
        :type read: SmartSsdReadLookahead
        """

        self._read = read

    @property
    def write(self) -> SmartSsdReadLookahead:
        """Gets the write of this SmartSsdAtaSctErc.


        :return: The write of this SmartSsdAtaSctErc.
        :rtype: SmartSsdReadLookahead
        """
        return self._write

    @write.setter
    def write(self, write: SmartSsdReadLookahead):
        """Sets the write of this SmartSsdAtaSctErc.


        :param write: The write of this SmartSsdAtaSctErc.
        :type write: SmartSsdReadLookahead
        """

        self._write = write
