# coding: utf-8

"""
    Ceph SMART Metrics

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.smart_ssd_ata_smart_error_log_extended import SmartSsdAtaSmartErrorLogExtended  # noqa: F401,E501


class SmartSsdAtaSmartErrorLog(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'extended': 'SmartSsdAtaSmartErrorLogExtended'
    }

    attribute_map = {
        'extended': 'extended'
    }

    def __init__(self, extended=None):  # noqa: E501
        """SmartSsdAtaSmartErrorLog - a model defined in Swagger"""  # noqa: E501

        self._extended = None
        self.discriminator = None

        if extended is not None:
            self.extended = extended

    @property
    def extended(self):
        """Gets the extended of this SmartSsdAtaSmartErrorLog.  # noqa: E501


        :return: The extended of this SmartSsdAtaSmartErrorLog.  # noqa: E501
        :rtype: SmartSsdAtaSmartErrorLogExtended
        """
        return self._extended

    @extended.setter
    def extended(self, extended):
        """Sets the extended of this SmartSsdAtaSmartErrorLog.


        :param extended: The extended of this SmartSsdAtaSmartErrorLog.  # noqa: E501
        :type: SmartSsdAtaSmartErrorLogExtended
        """

        self._extended = extended

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SmartSsdAtaSmartErrorLog):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
