# coding: utf-8

"""
    Ceph SMART Metrics

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SmartSsdAtaSctTemperatureHistoryTemperature(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'op_limit_min': 'int',
        'op_limit_max': 'int',
        'limit_min': 'int',
        'limit_max': 'int'
    }

    attribute_map = {
        'op_limit_min': 'op_limit_min',
        'op_limit_max': 'op_limit_max',
        'limit_min': 'limit_min',
        'limit_max': 'limit_max'
    }

    def __init__(self, op_limit_min=None, op_limit_max=None, limit_min=None, limit_max=None):  # noqa: E501
        """SmartSsdAtaSctTemperatureHistoryTemperature - a model defined in Swagger"""  # noqa: E501

        self._op_limit_min = None
        self._op_limit_max = None
        self._limit_min = None
        self._limit_max = None
        self.discriminator = None

        if op_limit_min is not None:
            self.op_limit_min = op_limit_min
        if op_limit_max is not None:
            self.op_limit_max = op_limit_max
        if limit_min is not None:
            self.limit_min = limit_min
        if limit_max is not None:
            self.limit_max = limit_max

    @property
    def op_limit_min(self):
        """Gets the op_limit_min of this SmartSsdAtaSctTemperatureHistoryTemperature.  # noqa: E501


        :return: The op_limit_min of this SmartSsdAtaSctTemperatureHistoryTemperature.  # noqa: E501
        :rtype: int
        """
        return self._op_limit_min

    @op_limit_min.setter
    def op_limit_min(self, op_limit_min):
        """Sets the op_limit_min of this SmartSsdAtaSctTemperatureHistoryTemperature.


        :param op_limit_min: The op_limit_min of this SmartSsdAtaSctTemperatureHistoryTemperature.  # noqa: E501
        :type: int
        """

        self._op_limit_min = op_limit_min

    @property
    def op_limit_max(self):
        """Gets the op_limit_max of this SmartSsdAtaSctTemperatureHistoryTemperature.  # noqa: E501


        :return: The op_limit_max of this SmartSsdAtaSctTemperatureHistoryTemperature.  # noqa: E501
        :rtype: int
        """
        return self._op_limit_max

    @op_limit_max.setter
    def op_limit_max(self, op_limit_max):
        """Sets the op_limit_max of this SmartSsdAtaSctTemperatureHistoryTemperature.


        :param op_limit_max: The op_limit_max of this SmartSsdAtaSctTemperatureHistoryTemperature.  # noqa: E501
        :type: int
        """

        self._op_limit_max = op_limit_max

    @property
    def limit_min(self):
        """Gets the limit_min of this SmartSsdAtaSctTemperatureHistoryTemperature.  # noqa: E501


        :return: The limit_min of this SmartSsdAtaSctTemperatureHistoryTemperature.  # noqa: E501
        :rtype: int
        """
        return self._limit_min

    @limit_min.setter
    def limit_min(self, limit_min):
        """Sets the limit_min of this SmartSsdAtaSctTemperatureHistoryTemperature.


        :param limit_min: The limit_min of this SmartSsdAtaSctTemperatureHistoryTemperature.  # noqa: E501
        :type: int
        """

        self._limit_min = limit_min

    @property
    def limit_max(self):
        """Gets the limit_max of this SmartSsdAtaSctTemperatureHistoryTemperature.  # noqa: E501


        :return: The limit_max of this SmartSsdAtaSctTemperatureHistoryTemperature.  # noqa: E501
        :rtype: int
        """
        return self._limit_max

    @limit_max.setter
    def limit_max(self, limit_max):
        """Sets the limit_max of this SmartSsdAtaSctTemperatureHistoryTemperature.


        :param limit_max: The limit_max of this SmartSsdAtaSctTemperatureHistoryTemperature.  # noqa: E501
        :type: int
        """

        self._limit_max = limit_max

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SmartSsdAtaSctTemperatureHistoryTemperature):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
