# coding: utf-8

"""
    Ceph SMART Metrics

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.smart_ssd_ata_smart_data_offline_data_collection_status import SmartSsdAtaSmartDataOfflineDataCollectionStatus  # noqa: F401,E501


class SmartSsdAtaSmartDataOfflineDataCollection(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'SmartSsdAtaSmartDataOfflineDataCollectionStatus',
        'completion_seconds': 'int'
    }

    attribute_map = {
        'status': 'status',
        'completion_seconds': 'completion_seconds'
    }

    def __init__(self, status=None, completion_seconds=None):  # noqa: E501
        """SmartSsdAtaSmartDataOfflineDataCollection - a model defined in Swagger"""  # noqa: E501

        self._status = None
        self._completion_seconds = None
        self.discriminator = None

        if status is not None:
            self.status = status
        if completion_seconds is not None:
            self.completion_seconds = completion_seconds

    @property
    def status(self):
        """Gets the status of this SmartSsdAtaSmartDataOfflineDataCollection.  # noqa: E501


        :return: The status of this SmartSsdAtaSmartDataOfflineDataCollection.  # noqa: E501
        :rtype: SmartSsdAtaSmartDataOfflineDataCollectionStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this SmartSsdAtaSmartDataOfflineDataCollection.


        :param status: The status of this SmartSsdAtaSmartDataOfflineDataCollection.  # noqa: E501
        :type: SmartSsdAtaSmartDataOfflineDataCollectionStatus
        """

        self._status = status

    @property
    def completion_seconds(self):
        """Gets the completion_seconds of this SmartSsdAtaSmartDataOfflineDataCollection.  # noqa: E501


        :return: The completion_seconds of this SmartSsdAtaSmartDataOfflineDataCollection.  # noqa: E501
        :rtype: int
        """
        return self._completion_seconds

    @completion_seconds.setter
    def completion_seconds(self, completion_seconds):
        """Sets the completion_seconds of this SmartSsdAtaSmartDataOfflineDataCollection.


        :param completion_seconds: The completion_seconds of this SmartSsdAtaSmartDataOfflineDataCollection.  # noqa: E501
        :type: int
        """

        self._completion_seconds = completion_seconds

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SmartSsdAtaSmartDataOfflineDataCollection):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
