# coding: utf-8

"""
    Ceph SMART Metrics

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SmartSsdSataPhyEventCountersTable(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'size': 'int',
        'value': 'int',
        'overflow': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'size': 'size',
        'value': 'value',
        'overflow': 'overflow'
    }

    def __init__(self, id=None, name=None, size=None, value=None, overflow=None):  # noqa: E501
        """SmartSsdSataPhyEventCountersTable - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._size = None
        self._value = None
        self._overflow = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if size is not None:
            self.size = size
        if value is not None:
            self.value = value
        if overflow is not None:
            self.overflow = overflow

    @property
    def id(self):
        """Gets the id of this SmartSsdSataPhyEventCountersTable.  # noqa: E501


        :return: The id of this SmartSsdSataPhyEventCountersTable.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SmartSsdSataPhyEventCountersTable.


        :param id: The id of this SmartSsdSataPhyEventCountersTable.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this SmartSsdSataPhyEventCountersTable.  # noqa: E501


        :return: The name of this SmartSsdSataPhyEventCountersTable.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SmartSsdSataPhyEventCountersTable.


        :param name: The name of this SmartSsdSataPhyEventCountersTable.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def size(self):
        """Gets the size of this SmartSsdSataPhyEventCountersTable.  # noqa: E501


        :return: The size of this SmartSsdSataPhyEventCountersTable.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this SmartSsdSataPhyEventCountersTable.


        :param size: The size of this SmartSsdSataPhyEventCountersTable.  # noqa: E501
        :type: int
        """

        self._size = size

    @property
    def value(self):
        """Gets the value of this SmartSsdSataPhyEventCountersTable.  # noqa: E501


        :return: The value of this SmartSsdSataPhyEventCountersTable.  # noqa: E501
        :rtype: int
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this SmartSsdSataPhyEventCountersTable.


        :param value: The value of this SmartSsdSataPhyEventCountersTable.  # noqa: E501
        :type: int
        """

        self._value = value

    @property
    def overflow(self):
        """Gets the overflow of this SmartSsdSataPhyEventCountersTable.  # noqa: E501


        :return: The overflow of this SmartSsdSataPhyEventCountersTable.  # noqa: E501
        :rtype: bool
        """
        return self._overflow

    @overflow.setter
    def overflow(self, overflow):
        """Sets the overflow of this SmartSsdSataPhyEventCountersTable.


        :param overflow: The overflow of this SmartSsdSataPhyEventCountersTable.  # noqa: E501
        :type: bool
        """

        self._overflow = overflow

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SmartSsdSataPhyEventCountersTable):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
