# coding: utf-8

"""
    Ceph SMART Metrics

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.smart_ssd_ata_smart_attributes_table import SmartSsdAtaSmartAttributesTable  # noqa: F401,E501


class SmartSsdAtaSmartAttributes(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'revision': 'int',
        'table': 'list[SmartSsdAtaSmartAttributesTable]'
    }

    attribute_map = {
        'revision': 'revision',
        'table': 'table'
    }

    def __init__(self, revision=None, table=None):  # noqa: E501
        """SmartSsdAtaSmartAttributes - a model defined in Swagger"""  # noqa: E501

        self._revision = None
        self._table = None
        self.discriminator = None

        if revision is not None:
            self.revision = revision
        if table is not None:
            self.table = table

    @property
    def revision(self):
        """Gets the revision of this SmartSsdAtaSmartAttributes.  # noqa: E501


        :return: The revision of this SmartSsdAtaSmartAttributes.  # noqa: E501
        :rtype: int
        """
        return self._revision

    @revision.setter
    def revision(self, revision):
        """Sets the revision of this SmartSsdAtaSmartAttributes.


        :param revision: The revision of this SmartSsdAtaSmartAttributes.  # noqa: E501
        :type: int
        """

        self._revision = revision

    @property
    def table(self):
        """Gets the table of this SmartSsdAtaSmartAttributes.  # noqa: E501


        :return: The table of this SmartSsdAtaSmartAttributes.  # noqa: E501
        :rtype: list[SmartSsdAtaSmartAttributesTable]
        """
        return self._table

    @table.setter
    def table(self, table):
        """Sets the table of this SmartSsdAtaSmartAttributes.


        :param table: The table of this SmartSsdAtaSmartAttributes.  # noqa: E501
        :type: list[SmartSsdAtaSmartAttributesTable]
        """

        self._table = table

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SmartSsdAtaSmartAttributes):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
