# coding: utf-8

"""
    Ceph SMART Metrics

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.smart_ssd_user_capacity_blocks import SmartSsdUserCapacityBlocks  # noqa: F401,E501
from swagger_client.models.smart_ssd_user_capacity_bytes import SmartSsdUserCapacityBytes  # noqa: F401,E501


class SmartSsdUserCapacity(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'blocks': 'SmartSsdUserCapacityBlocks',
        'bytes': 'SmartSsdUserCapacityBytes'
    }

    attribute_map = {
        'blocks': 'blocks',
        'bytes': 'bytes'
    }

    def __init__(self, blocks=None, bytes=None):  # noqa: E501
        """SmartSsdUserCapacity - a model defined in Swagger"""  # noqa: E501

        self._blocks = None
        self._bytes = None
        self.discriminator = None

        if blocks is not None:
            self.blocks = blocks
        if bytes is not None:
            self.bytes = bytes

    @property
    def blocks(self):
        """Gets the blocks of this SmartSsdUserCapacity.  # noqa: E501


        :return: The blocks of this SmartSsdUserCapacity.  # noqa: E501
        :rtype: SmartSsdUserCapacityBlocks
        """
        return self._blocks

    @blocks.setter
    def blocks(self, blocks):
        """Sets the blocks of this SmartSsdUserCapacity.


        :param blocks: The blocks of this SmartSsdUserCapacity.  # noqa: E501
        :type: SmartSsdUserCapacityBlocks
        """

        self._blocks = blocks

    @property
    def bytes(self):
        """Gets the bytes of this SmartSsdUserCapacity.  # noqa: E501


        :return: The bytes of this SmartSsdUserCapacity.  # noqa: E501
        :rtype: SmartSsdUserCapacityBytes
        """
        return self._bytes

    @bytes.setter
    def bytes(self, bytes):
        """Sets the bytes of this SmartSsdUserCapacity.


        :param bytes: The bytes of this SmartSsdUserCapacity.  # noqa: E501
        :type: SmartSsdUserCapacityBytes
        """

        self._bytes = bytes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SmartSsdUserCapacity):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
