# coding: utf-8

"""
    Ceph SMART Metrics

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.smart_ssd_ata_smart_data_self_test_polling_minutes import SmartSsdAtaSmartDataSelfTestPollingMinutes  # noqa: F401,E501
from swagger_client.models.smart_ssd_ata_smart_data_self_test_status import SmartSsdAtaSmartDataSelfTestStatus  # noqa: F401,E501


class SmartSsdAtaSmartDataSelfTest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'SmartSsdAtaSmartDataSelfTestStatus',
        'polling_minutes': 'SmartSsdAtaSmartDataSelfTestPollingMinutes'
    }

    attribute_map = {
        'status': 'status',
        'polling_minutes': 'polling_minutes'
    }

    def __init__(self, status=None, polling_minutes=None):  # noqa: E501
        """SmartSsdAtaSmartDataSelfTest - a model defined in Swagger"""  # noqa: E501

        self._status = None
        self._polling_minutes = None
        self.discriminator = None

        if status is not None:
            self.status = status
        if polling_minutes is not None:
            self.polling_minutes = polling_minutes

    @property
    def status(self):
        """Gets the status of this SmartSsdAtaSmartDataSelfTest.  # noqa: E501


        :return: The status of this SmartSsdAtaSmartDataSelfTest.  # noqa: E501
        :rtype: SmartSsdAtaSmartDataSelfTestStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this SmartSsdAtaSmartDataSelfTest.


        :param status: The status of this SmartSsdAtaSmartDataSelfTest.  # noqa: E501
        :type: SmartSsdAtaSmartDataSelfTestStatus
        """

        self._status = status

    @property
    def polling_minutes(self):
        """Gets the polling_minutes of this SmartSsdAtaSmartDataSelfTest.  # noqa: E501


        :return: The polling_minutes of this SmartSsdAtaSmartDataSelfTest.  # noqa: E501
        :rtype: SmartSsdAtaSmartDataSelfTestPollingMinutes
        """
        return self._polling_minutes

    @polling_minutes.setter
    def polling_minutes(self, polling_minutes):
        """Sets the polling_minutes of this SmartSsdAtaSmartDataSelfTest.


        :param polling_minutes: The polling_minutes of this SmartSsdAtaSmartDataSelfTest.  # noqa: E501
        :type: SmartSsdAtaSmartDataSelfTestPollingMinutes
        """

        self._polling_minutes = polling_minutes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SmartSsdAtaSmartDataSelfTest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
