# coding: utf-8

"""
    Ceph SMART Metrics

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.smart_ssd_sata_phy_event_counters_table import SmartSsdSataPhyEventCountersTable  # noqa: F401,E501


class SmartSsdSataPhyEventCounters(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'table': 'list[SmartSsdSataPhyEventCountersTable]',
        'reset': 'bool'
    }

    attribute_map = {
        'table': 'table',
        'reset': 'reset'
    }

    def __init__(self, table=None, reset=None):  # noqa: E501
        """SmartSsdSataPhyEventCounters - a model defined in Swagger"""  # noqa: E501

        self._table = None
        self._reset = None
        self.discriminator = None

        if table is not None:
            self.table = table
        if reset is not None:
            self.reset = reset

    @property
    def table(self):
        """Gets the table of this SmartSsdSataPhyEventCounters.  # noqa: E501


        :return: The table of this SmartSsdSataPhyEventCounters.  # noqa: E501
        :rtype: list[SmartSsdSataPhyEventCountersTable]
        """
        return self._table

    @table.setter
    def table(self, table):
        """Sets the table of this SmartSsdSataPhyEventCounters.


        :param table: The table of this SmartSsdSataPhyEventCounters.  # noqa: E501
        :type: list[SmartSsdSataPhyEventCountersTable]
        """

        self._table = table

    @property
    def reset(self):
        """Gets the reset of this SmartSsdSataPhyEventCounters.  # noqa: E501


        :return: The reset of this SmartSsdSataPhyEventCounters.  # noqa: E501
        :rtype: bool
        """
        return self._reset

    @reset.setter
    def reset(self, reset):
        """Sets the reset of this SmartSsdSataPhyEventCounters.


        :param reset: The reset of this SmartSsdSataPhyEventCounters.  # noqa: E501
        :type: bool
        """

        self._reset = reset

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SmartSsdSataPhyEventCounters):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
