# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.smart_ssd_ata_smart_data_self_test_polling_minutes import SmartSsdAtaSmartDataSelfTestPollingMinutes  # noqa: F401,E501
from swagger_server.models.smart_ssd_ata_smart_data_self_test_status import SmartSsdAtaSmartDataSelfTestStatus  # noqa: F401,E501
from swagger_server import util


class SmartSsdAtaSmartDataSelfTest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, status: SmartSsdAtaSmartDataSelfTestStatus=None, polling_minutes: SmartSsdAtaSmartDataSelfTestPollingMinutes=None):  # noqa: E501
        """SmartSsdAtaSmartDataSelfTest - a model defined in Swagger

        :param status: The status of this SmartSsdAtaSmartDataSelfTest.  # noqa: E501
        :type status: SmartSsdAtaSmartDataSelfTestStatus
        :param polling_minutes: The polling_minutes of this SmartSsdAtaSmartDataSelfTest.  # noqa: E501
        :type polling_minutes: SmartSsdAtaSmartDataSelfTestPollingMinutes
        """
        self.swagger_types = {
            'status': SmartSsdAtaSmartDataSelfTestStatus,
            'polling_minutes': SmartSsdAtaSmartDataSelfTestPollingMinutes
        }

        self.attribute_map = {
            'status': 'status',
            'polling_minutes': 'polling_minutes'
        }

        self._status = status
        self._polling_minutes = polling_minutes

    @classmethod
    def from_dict(cls, dikt) -> 'SmartSsdAtaSmartDataSelfTest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SmartSsd_ata_smart_data_self_test of this SmartSsdAtaSmartDataSelfTest.  # noqa: E501
        :rtype: SmartSsdAtaSmartDataSelfTest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> SmartSsdAtaSmartDataSelfTestStatus:
        """Gets the status of this SmartSsdAtaSmartDataSelfTest.


        :return: The status of this SmartSsdAtaSmartDataSelfTest.
        :rtype: SmartSsdAtaSmartDataSelfTestStatus
        """
        return self._status

    @status.setter
    def status(self, status: SmartSsdAtaSmartDataSelfTestStatus):
        """Sets the status of this SmartSsdAtaSmartDataSelfTest.


        :param status: The status of this SmartSsdAtaSmartDataSelfTest.
        :type status: SmartSsdAtaSmartDataSelfTestStatus
        """

        self._status = status

    @property
    def polling_minutes(self) -> SmartSsdAtaSmartDataSelfTestPollingMinutes:
        """Gets the polling_minutes of this SmartSsdAtaSmartDataSelfTest.


        :return: The polling_minutes of this SmartSsdAtaSmartDataSelfTest.
        :rtype: SmartSsdAtaSmartDataSelfTestPollingMinutes
        """
        return self._polling_minutes

    @polling_minutes.setter
    def polling_minutes(self, polling_minutes: SmartSsdAtaSmartDataSelfTestPollingMinutes):
        """Sets the polling_minutes of this SmartSsdAtaSmartDataSelfTest.


        :param polling_minutes: The polling_minutes of this SmartSsdAtaSmartDataSelfTest.
        :type polling_minutes: SmartSsdAtaSmartDataSelfTestPollingMinutes
        """

        self._polling_minutes = polling_minutes
