# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SmartSsdAtaSecurity(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, state: int=None, string: str=None, enabled: bool=None, frozen: bool=None):  # noqa: E501
        """SmartSsdAtaSecurity - a model defined in Swagger

        :param state: The state of this SmartSsdAtaSecurity.  # noqa: E501
        :type state: int
        :param string: The string of this SmartSsdAtaSecurity.  # noqa: E501
        :type string: str
        :param enabled: The enabled of this SmartSsdAtaSecurity.  # noqa: E501
        :type enabled: bool
        :param frozen: The frozen of this SmartSsdAtaSecurity.  # noqa: E501
        :type frozen: bool
        """
        self.swagger_types = {
            'state': int,
            'string': str,
            'enabled': bool,
            'frozen': bool
        }

        self.attribute_map = {
            'state': 'state',
            'string': 'string',
            'enabled': 'enabled',
            'frozen': 'frozen'
        }

        self._state = state
        self._string = string
        self._enabled = enabled
        self._frozen = frozen

    @classmethod
    def from_dict(cls, dikt) -> 'SmartSsdAtaSecurity':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SmartSsd_ata_security of this SmartSsdAtaSecurity.  # noqa: E501
        :rtype: SmartSsdAtaSecurity
        """
        return util.deserialize_model(dikt, cls)

    @property
    def state(self) -> int:
        """Gets the state of this SmartSsdAtaSecurity.


        :return: The state of this SmartSsdAtaSecurity.
        :rtype: int
        """
        return self._state

    @state.setter
    def state(self, state: int):
        """Sets the state of this SmartSsdAtaSecurity.


        :param state: The state of this SmartSsdAtaSecurity.
        :type state: int
        """

        self._state = state

    @property
    def string(self) -> str:
        """Gets the string of this SmartSsdAtaSecurity.


        :return: The string of this SmartSsdAtaSecurity.
        :rtype: str
        """
        return self._string

    @string.setter
    def string(self, string: str):
        """Sets the string of this SmartSsdAtaSecurity.


        :param string: The string of this SmartSsdAtaSecurity.
        :type string: str
        """

        self._string = string

    @property
    def enabled(self) -> bool:
        """Gets the enabled of this SmartSsdAtaSecurity.


        :return: The enabled of this SmartSsdAtaSecurity.
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled: bool):
        """Sets the enabled of this SmartSsdAtaSecurity.


        :param enabled: The enabled of this SmartSsdAtaSecurity.
        :type enabled: bool
        """

        self._enabled = enabled

    @property
    def frozen(self) -> bool:
        """Gets the frozen of this SmartSsdAtaSecurity.


        :return: The frozen of this SmartSsdAtaSecurity.
        :rtype: bool
        """
        return self._frozen

    @frozen.setter
    def frozen(self, frozen: bool):
        """Sets the frozen of this SmartSsdAtaSecurity.


        :param frozen: The frozen of this SmartSsdAtaSecurity.
        :type frozen: bool
        """

        self._frozen = frozen
