# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SmartSsdFormFactor(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, ata_value: int=None, name: str=None):  # noqa: E501
        """SmartSsdFormFactor - a model defined in Swagger

        :param ata_value: The ata_value of this SmartSsdFormFactor.  # noqa: E501
        :type ata_value: int
        :param name: The name of this SmartSsdFormFactor.  # noqa: E501
        :type name: str
        """
        self.swagger_types = {
            'ata_value': int,
            'name': str
        }

        self.attribute_map = {
            'ata_value': 'ata_value',
            'name': 'name'
        }

        self._ata_value = ata_value
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'SmartSsdFormFactor':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SmartSsd_form_factor of this SmartSsdFormFactor.  # noqa: E501
        :rtype: SmartSsdFormFactor
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ata_value(self) -> int:
        """Gets the ata_value of this SmartSsdFormFactor.


        :return: The ata_value of this SmartSsdFormFactor.
        :rtype: int
        """
        return self._ata_value

    @ata_value.setter
    def ata_value(self, ata_value: int):
        """Sets the ata_value of this SmartSsdFormFactor.


        :param ata_value: The ata_value of this SmartSsdFormFactor.
        :type ata_value: int
        """

        self._ata_value = ata_value

    @property
    def name(self) -> str:
        """Gets the name of this SmartSsdFormFactor.


        :return: The name of this SmartSsdFormFactor.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this SmartSsdFormFactor.


        :param name: The name of this SmartSsdFormFactor.
        :type name: str
        """

        self._name = name
