# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SmartSsdAtaSmartAttributesFlags(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, value: int=None, string: str=None, prefailure: bool=None, updated_online: bool=None, performance: bool=None, error_rate: bool=None, event_count: bool=None, auto_keep: bool=None):  # noqa: E501
        """SmartSsdAtaSmartAttributesFlags - a model defined in Swagger

        :param value: The value of this SmartSsdAtaSmartAttributesFlags.  # noqa: E501
        :type value: int
        :param string: The string of this SmartSsdAtaSmartAttributesFlags.  # noqa: E501
        :type string: str
        :param prefailure: The prefailure of this SmartSsdAtaSmartAttributesFlags.  # noqa: E501
        :type prefailure: bool
        :param updated_online: The updated_online of this SmartSsdAtaSmartAttributesFlags.  # noqa: E501
        :type updated_online: bool
        :param performance: The performance of this SmartSsdAtaSmartAttributesFlags.  # noqa: E501
        :type performance: bool
        :param error_rate: The error_rate of this SmartSsdAtaSmartAttributesFlags.  # noqa: E501
        :type error_rate: bool
        :param event_count: The event_count of this SmartSsdAtaSmartAttributesFlags.  # noqa: E501
        :type event_count: bool
        :param auto_keep: The auto_keep of this SmartSsdAtaSmartAttributesFlags.  # noqa: E501
        :type auto_keep: bool
        """
        self.swagger_types = {
            'value': int,
            'string': str,
            'prefailure': bool,
            'updated_online': bool,
            'performance': bool,
            'error_rate': bool,
            'event_count': bool,
            'auto_keep': bool
        }

        self.attribute_map = {
            'value': 'value',
            'string': 'string',
            'prefailure': 'prefailure',
            'updated_online': 'updated_online',
            'performance': 'performance',
            'error_rate': 'error_rate',
            'event_count': 'event_count',
            'auto_keep': 'auto_keep'
        }

        self._value = value
        self._string = string
        self._prefailure = prefailure
        self._updated_online = updated_online
        self._performance = performance
        self._error_rate = error_rate
        self._event_count = event_count
        self._auto_keep = auto_keep

    @classmethod
    def from_dict(cls, dikt) -> 'SmartSsdAtaSmartAttributesFlags':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SmartSsd_ata_smart_attributes_flags of this SmartSsdAtaSmartAttributesFlags.  # noqa: E501
        :rtype: SmartSsdAtaSmartAttributesFlags
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self) -> int:
        """Gets the value of this SmartSsdAtaSmartAttributesFlags.


        :return: The value of this SmartSsdAtaSmartAttributesFlags.
        :rtype: int
        """
        return self._value

    @value.setter
    def value(self, value: int):
        """Sets the value of this SmartSsdAtaSmartAttributesFlags.


        :param value: The value of this SmartSsdAtaSmartAttributesFlags.
        :type value: int
        """

        self._value = value

    @property
    def string(self) -> str:
        """Gets the string of this SmartSsdAtaSmartAttributesFlags.


        :return: The string of this SmartSsdAtaSmartAttributesFlags.
        :rtype: str
        """
        return self._string

    @string.setter
    def string(self, string: str):
        """Sets the string of this SmartSsdAtaSmartAttributesFlags.


        :param string: The string of this SmartSsdAtaSmartAttributesFlags.
        :type string: str
        """

        self._string = string

    @property
    def prefailure(self) -> bool:
        """Gets the prefailure of this SmartSsdAtaSmartAttributesFlags.


        :return: The prefailure of this SmartSsdAtaSmartAttributesFlags.
        :rtype: bool
        """
        return self._prefailure

    @prefailure.setter
    def prefailure(self, prefailure: bool):
        """Sets the prefailure of this SmartSsdAtaSmartAttributesFlags.


        :param prefailure: The prefailure of this SmartSsdAtaSmartAttributesFlags.
        :type prefailure: bool
        """

        self._prefailure = prefailure

    @property
    def updated_online(self) -> bool:
        """Gets the updated_online of this SmartSsdAtaSmartAttributesFlags.


        :return: The updated_online of this SmartSsdAtaSmartAttributesFlags.
        :rtype: bool
        """
        return self._updated_online

    @updated_online.setter
    def updated_online(self, updated_online: bool):
        """Sets the updated_online of this SmartSsdAtaSmartAttributesFlags.


        :param updated_online: The updated_online of this SmartSsdAtaSmartAttributesFlags.
        :type updated_online: bool
        """

        self._updated_online = updated_online

    @property
    def performance(self) -> bool:
        """Gets the performance of this SmartSsdAtaSmartAttributesFlags.


        :return: The performance of this SmartSsdAtaSmartAttributesFlags.
        :rtype: bool
        """
        return self._performance

    @performance.setter
    def performance(self, performance: bool):
        """Sets the performance of this SmartSsdAtaSmartAttributesFlags.


        :param performance: The performance of this SmartSsdAtaSmartAttributesFlags.
        :type performance: bool
        """

        self._performance = performance

    @property
    def error_rate(self) -> bool:
        """Gets the error_rate of this SmartSsdAtaSmartAttributesFlags.


        :return: The error_rate of this SmartSsdAtaSmartAttributesFlags.
        :rtype: bool
        """
        return self._error_rate

    @error_rate.setter
    def error_rate(self, error_rate: bool):
        """Sets the error_rate of this SmartSsdAtaSmartAttributesFlags.


        :param error_rate: The error_rate of this SmartSsdAtaSmartAttributesFlags.
        :type error_rate: bool
        """

        self._error_rate = error_rate

    @property
    def event_count(self) -> bool:
        """Gets the event_count of this SmartSsdAtaSmartAttributesFlags.


        :return: The event_count of this SmartSsdAtaSmartAttributesFlags.
        :rtype: bool
        """
        return self._event_count

    @event_count.setter
    def event_count(self, event_count: bool):
        """Sets the event_count of this SmartSsdAtaSmartAttributesFlags.


        :param event_count: The event_count of this SmartSsdAtaSmartAttributesFlags.
        :type event_count: bool
        """

        self._event_count = event_count

    @property
    def auto_keep(self) -> bool:
        """Gets the auto_keep of this SmartSsdAtaSmartAttributesFlags.


        :return: The auto_keep of this SmartSsdAtaSmartAttributesFlags.
        :rtype: bool
        """
        return self._auto_keep

    @auto_keep.setter
    def auto_keep(self, auto_keep: bool):
        """Sets the auto_keep of this SmartSsdAtaSmartAttributesFlags.


        :param auto_keep: The auto_keep of this SmartSsdAtaSmartAttributesFlags.
        :type auto_keep: bool
        """

        self._auto_keep = auto_keep
