# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SmartSsdSmartStatus(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, passed: bool=None):  # noqa: E501
        """SmartSsdSmartStatus - a model defined in Swagger

        :param passed: The passed of this SmartSsdSmartStatus.  # noqa: E501
        :type passed: bool
        """
        self.swagger_types = {
            'passed': bool
        }

        self.attribute_map = {
            'passed': 'passed'
        }

        self._passed = passed

    @classmethod
    def from_dict(cls, dikt) -> 'SmartSsdSmartStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SmartSsd_smart_status of this SmartSsdSmartStatus.  # noqa: E501
        :rtype: SmartSsdSmartStatus
        """
        return util.deserialize_model(dikt, cls)

    @property
    def passed(self) -> bool:
        """Gets the passed of this SmartSsdSmartStatus.


        :return: The passed of this SmartSsdSmartStatus.
        :rtype: bool
        """
        return self._passed

    @passed.setter
    def passed(self, passed: bool):
        """Sets the passed of this SmartSsdSmartStatus.


        :param passed: The passed of this SmartSsdSmartStatus.
        :type passed: bool
        """

        self._passed = passed
