# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SmartSsdAtaVersion(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, string: str=None, major_value: int=None, minor_value: int=None):  # noqa: E501
        """SmartSsdAtaVersion - a model defined in Swagger

        :param string: The string of this SmartSsdAtaVersion.  # noqa: E501
        :type string: str
        :param major_value: The major_value of this SmartSsdAtaVersion.  # noqa: E501
        :type major_value: int
        :param minor_value: The minor_value of this SmartSsdAtaVersion.  # noqa: E501
        :type minor_value: int
        """
        self.swagger_types = {
            'string': str,
            'major_value': int,
            'minor_value': int
        }

        self.attribute_map = {
            'string': 'string',
            'major_value': 'major_value',
            'minor_value': 'minor_value'
        }

        self._string = string
        self._major_value = major_value
        self._minor_value = minor_value

    @classmethod
    def from_dict(cls, dikt) -> 'SmartSsdAtaVersion':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SmartSsd_ata_version of this SmartSsdAtaVersion.  # noqa: E501
        :rtype: SmartSsdAtaVersion
        """
        return util.deserialize_model(dikt, cls)

    @property
    def string(self) -> str:
        """Gets the string of this SmartSsdAtaVersion.


        :return: The string of this SmartSsdAtaVersion.
        :rtype: str
        """
        return self._string

    @string.setter
    def string(self, string: str):
        """Sets the string of this SmartSsdAtaVersion.


        :param string: The string of this SmartSsdAtaVersion.
        :type string: str
        """

        self._string = string

    @property
    def major_value(self) -> int:
        """Gets the major_value of this SmartSsdAtaVersion.


        :return: The major_value of this SmartSsdAtaVersion.
        :rtype: int
        """
        return self._major_value

    @major_value.setter
    def major_value(self, major_value: int):
        """Sets the major_value of this SmartSsdAtaVersion.


        :param major_value: The major_value of this SmartSsdAtaVersion.
        :type major_value: int
        """

        self._major_value = major_value

    @property
    def minor_value(self) -> int:
        """Gets the minor_value of this SmartSsdAtaVersion.


        :return: The minor_value of this SmartSsdAtaVersion.
        :rtype: int
        """
        return self._minor_value

    @minor_value.setter
    def minor_value(self, minor_value: int):
        """Sets the minor_value of this SmartSsdAtaVersion.


        :param minor_value: The minor_value of this SmartSsdAtaVersion.
        :type minor_value: int
        """

        self._minor_value = minor_value
