# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SmartNvmeEui64(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, oui: int=None, ext_id: int=None):  # noqa: E501
        """SmartNvmeEui64 - a model defined in Swagger

        :param oui: The oui of this SmartNvmeEui64.  # noqa: E501
        :type oui: int
        :param ext_id: The ext_id of this SmartNvmeEui64.  # noqa: E501
        :type ext_id: int
        """
        self.swagger_types = {
            'oui': int,
            'ext_id': int
        }

        self.attribute_map = {
            'oui': 'oui',
            'ext_id': 'ext_id'
        }

        self._oui = oui
        self._ext_id = ext_id

    @classmethod
    def from_dict(cls, dikt) -> 'SmartNvmeEui64':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SmartNvme_eui64 of this SmartNvmeEui64.  # noqa: E501
        :rtype: SmartNvmeEui64
        """
        return util.deserialize_model(dikt, cls)

    @property
    def oui(self) -> int:
        """Gets the oui of this SmartNvmeEui64.


        :return: The oui of this SmartNvmeEui64.
        :rtype: int
        """
        return self._oui

    @oui.setter
    def oui(self, oui: int):
        """Sets the oui of this SmartNvmeEui64.


        :param oui: The oui of this SmartNvmeEui64.
        :type oui: int
        """

        self._oui = oui

    @property
    def ext_id(self) -> int:
        """Gets the ext_id of this SmartNvmeEui64.


        :return: The ext_id of this SmartNvmeEui64.
        :rtype: int
        """
        return self._ext_id

    @ext_id.setter
    def ext_id(self, ext_id: int):
        """Sets the ext_id of this SmartNvmeEui64.


        :param ext_id: The ext_id of this SmartNvmeEui64.
        :type ext_id: int
        """

        self._ext_id = ext_id
