# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SmartSsdInterfaceSpeedMax(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, string: str=None):  # noqa: E501
        """SmartSsdInterfaceSpeedMax - a model defined in Swagger

        :param string: The string of this SmartSsdInterfaceSpeedMax.  # noqa: E501
        :type string: str
        """
        self.swagger_types = {
            'string': str
        }

        self.attribute_map = {
            'string': 'string'
        }

        self._string = string

    @classmethod
    def from_dict(cls, dikt) -> 'SmartSsdInterfaceSpeedMax':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SmartSsd_interface_speed_max of this SmartSsdInterfaceSpeedMax.  # noqa: E501
        :rtype: SmartSsdInterfaceSpeedMax
        """
        return util.deserialize_model(dikt, cls)

    @property
    def string(self) -> str:
        """Gets the string of this SmartSsdInterfaceSpeedMax.


        :return: The string of this SmartSsdInterfaceSpeedMax.
        :rtype: str
        """
        return self._string

    @string.setter
    def string(self, string: str):
        """Sets the string of this SmartSsdInterfaceSpeedMax.


        :param string: The string of this SmartSsdInterfaceSpeedMax.
        :type string: str
        """

        self._string = string
