# coding: utf-8

"""
    Ceph SMART Metrics

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class SmartDataApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def add_smart_nvme(self, smart_nvme, **kwargs):  # noqa: E501
        """Upload NVME disk data  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.add_smart_nvme(smart_nvme, async=True)
        >>> result = thread.get()

        :param async bool
        :param SmartNvme smart_nvme: Smartctl --json -x output to be added to dataset (required)
        :param str uuid: Unique User ID
        :return: list[SmartNvme]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.add_smart_nvme_with_http_info(smart_nvme, **kwargs)  # noqa: E501
        else:
            (data) = self.add_smart_nvme_with_http_info(smart_nvme, **kwargs)  # noqa: E501
            return data

    def add_smart_nvme_with_http_info(self, smart_nvme, **kwargs):  # noqa: E501
        """Upload NVME disk data  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.add_smart_nvme_with_http_info(smart_nvme, async=True)
        >>> result = thread.get()

        :param async bool
        :param SmartNvme smart_nvme: Smartctl --json -x output to be added to dataset (required)
        :param str uuid: Unique User ID
        :return: list[SmartNvme]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['smart_nvme', 'uuid']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method add_smart_nvme" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'smart_nvme' is set
        if ('smart_nvme' not in params or
                params['smart_nvme'] is None):
            raise ValueError("Missing the required parameter `smart_nvme` when calling `add_smart_nvme`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'uuid' in params:
            query_params.append(('UUID', params['uuid']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'smart_nvme' in params:
            body_params = params['smart_nvme']
        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/smart-nvme', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[SmartNvme]',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def add_smart_ssd(self, smart_ssd, **kwargs):  # noqa: E501
        """Upload ssd disk data  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.add_smart_ssd(smart_ssd, async=True)
        >>> result = thread.get()

        :param async bool
        :param SmartSsd smart_ssd: Smartctl --json -x output to be added to dataset (required)
        :param str uuid: Unique User ID
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.add_smart_ssd_with_http_info(smart_ssd, **kwargs)  # noqa: E501
        else:
            (data) = self.add_smart_ssd_with_http_info(smart_ssd, **kwargs)  # noqa: E501
            return data

    def add_smart_ssd_with_http_info(self, smart_ssd, **kwargs):  # noqa: E501
        """Upload ssd disk data  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.add_smart_ssd_with_http_info(smart_ssd, async=True)
        >>> result = thread.get()

        :param async bool
        :param SmartSsd smart_ssd: Smartctl --json -x output to be added to dataset (required)
        :param str uuid: Unique User ID
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['smart_ssd', 'uuid']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method add_smart_ssd" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'smart_ssd' is set
        if ('smart_ssd' not in params or
                params['smart_ssd'] is None):
            raise ValueError("Missing the required parameter `smart_ssd` when calling `add_smart_ssd`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'uuid' in params:
            query_params.append(('UUID', params['uuid']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'smart_ssd' in params:
            body_params = params['smart_ssd']
        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/smart-ssd', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_smart_nvme(self, **kwargs):  # noqa: E501
        """Get all NVME disk data  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.get_smart_nvme(async=True)
        >>> result = thread.get()

        :param async bool
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.get_smart_nvme_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_smart_nvme_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_smart_nvme_with_http_info(self, **kwargs):  # noqa: E501
        """Get all NVME disk data  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.get_smart_nvme_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_smart_nvme" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/smart-nvme', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_smart_ssd(self, **kwargs):  # noqa: E501
        """Get all ssd disk data  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.get_smart_ssd(async=True)
        >>> result = thread.get()

        :param async bool
        :return: list[SmartSsd]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.get_smart_ssd_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_smart_ssd_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_smart_ssd_with_http_info(self, **kwargs):  # noqa: E501
        """Get all ssd disk data  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.get_smart_ssd_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :return: list[SmartSsd]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_smart_ssd" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/smart-ssd', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[SmartSsd]',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
